#import "FLXSVersion.h"
#import "FLXSPrintOptions.h"
/**
* Class to print the datagrid, either one page at a time <br/>
* or specific pages, or all pages.
*/
@class FLXSPrintOptions;

@protocol FLXSIPDFPrinter
/**
		 * Called when the Print controller is ready to send out the pages.
		 * @param printOptions The printOptions that started the pdf
		 */
-(void)beginDocument:(FLXSPrintOptions*)printOptions;
/**
* For each page generated by the Print Controller, this method is called.
* @param page The currently added page
* @param printOptions The printOptions that started the pdf
*/
- (void)addPage:(UIView *)page printOptions:(FLXSPrintOptions *)printOptions;
/**
		 * Once all pages are added to the doc, this method is called.
		 * @param printOptions The printOptions that started the pdf
		 */
-(void)endDocument:(FLXSPrintOptions*)printOptions;
@end

